[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[functions]]
  function = "scheduled-publish"
  schedule = "*/15 * * * *"
